import { Request, Response } from "express";
import PDFDocument from "pdfkit";
import prisma from "../config/db";

interface SaleItemSnapshot {
  productId: string;
  name: string;
  unitPrice: number;
  quantity: number;
}

const GOLD = "#B8860B"; // print-safe darker gold (screen #E3A008 is too light on white paper)
const INK = "#132A20";
const MUTED = "#6B7A72";

/**
 * GET /api/v1/invoices/:id/pdf
 * Ownership of :id already verified by requireOwnedResource('sale').
 * Streams the PDF directly rather than buffering it fully in memory first —
 * keeps memory flat regardless of invoice size, which matters on a
 * serverless function with a tight memory ceiling (Section 8.5).
 */
export async function downloadInvoicePdf(req: Request, res: Response) {
  const { id } = req.params;

  const sale = await prisma.sale.findUnique({
    where: { id },
    include: { shop: { select: { name: true, address: true } } },
  });

  if (!sale) {
    return res.status(404).json({ message: "Invoice not found." });
  }

  const items = (sale.items as SaleItemSnapshot[]) ?? [];

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${sale.invoiceNo}.pdf"`);

  const doc = new PDFDocument({ size: "A5", margin: 40 });
  doc.pipe(res);

  // Header
  doc
    .font("Helvetica-Bold")
    .fontSize(18)
    .fillColor(INK)
    .text(sale.shop.name, { align: "left" });

  if (sale.shop.address) {
    doc.font("Helvetica").fontSize(9).fillColor(MUTED).text(sale.shop.address);
  }

  doc.moveDown(0.5);
  doc
    .font("Helvetica-Bold")
    .fontSize(12)
    .fillColor(GOLD)
    .text(`Invoice ${sale.invoiceNo}`);

  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor(MUTED)
    .text(`Date: ${sale.timestamp.toLocaleString("en-BD")}`)
    .text(`Customer: ${sale.customerName}`);

  doc.moveDown();

  // Itemized table
  const tableTop = doc.y;
  const col = { item: 40, qty: 260, unit: 320, amount: 400 };

  doc
    .font("Helvetica-Bold")
    .fontSize(9)
    .fillColor(INK)
    .text("Item", col.item, tableTop)
    .text("Qty", col.qty, tableTop, { width: 50, align: "right" })
    .text("Unit", col.unit, tableTop, { width: 60, align: "right" })
    .text("Amount", col.amount, tableTop, { width: 80, align: "right" });

  doc
    .moveTo(40, tableTop + 14)
    .lineTo(480, tableTop + 14)
    .strokeColor("#CCCCCC")
    .stroke();

  let rowY = tableTop + 20;
  doc.font("Helvetica").fontSize(9).fillColor(INK);

  for (const item of items) {
    const lineTotal = item.unitPrice * item.quantity;
    doc
      .text(item.name, col.item, rowY, { width: 200 })
      .text(String(item.quantity), col.qty, rowY, { width: 50, align: "right" })
      .text(`৳${item.unitPrice.toLocaleString()}`, col.unit, rowY, { width: 60, align: "right" })
      .text(`৳${lineTotal.toLocaleString()}`, col.amount, rowY, { width: 80, align: "right" });
    rowY += 18;
  }

  doc
    .moveTo(40, rowY + 4)
    .lineTo(480, rowY + 4)
    .strokeColor("#CCCCCC")
    .stroke();

  doc
    .font("Helvetica-Bold")
    .fontSize(12)
    .fillColor(INK)
    .text("Total", col.unit, rowY + 14, { width: 60, align: "right" })
    .fillColor(GOLD)
    .text(`৳${sale.totalAmount.toLocaleString()}`, col.amount, rowY + 14, {
      width: 80,
      align: "right",
    });

  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor(sale.paymentType === "CREDIT" ? "#B33A1E" : "#2F8F5B")
    .text(
      sale.paymentType === "CREDIT" ? "Payment status: On credit (baki)" : "Payment status: Paid in full",
      col.item,
      rowY + 40
    );

  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(MUTED)
    .text("Generated by DokanKhata AI", col.item, rowY + 70);

  doc.end();
}